M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-12T06:35:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T06:35:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X9.0Y-9.0
X135.0Y-136.0
X160.0Y-9.0
X160.0Y-136.0
M30
