TRACKS = 80
SECTORS_PER_TRACK = 32
RECORD_BYTES = 128
RESERVED_TRACKS = 2
DRIVE_COUNT = 4

DPB_BSH = 4
DPB_BLM = 15
DPB_EXM = 0
DPB_DSM = 155
DPB_DRM = 63
DPB_AL0 = 0x80
DPB_AL1 = 0x00
DPB_CKS = 0

RECORD_COUNT = TRACKS * SECTORS_PER_TRACK
IMAGE_BYTES = RECORD_COUNT * RECORD_BYTES
SYSTEM_BYTES = RESERVED_TRACKS * SECTORS_PER_TRACK * RECORD_BYTES

assert IMAGE_BYTES == 327680
assert (TRACKS - RESERVED_TRACKS) * SECTORS_PER_TRACK == (
    DPB_DSM + 1
) * (1 << DPB_BSH)
