name: Build and Deploy Documentation

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    env:
      REQUIREMENTS: docs/docs/requirements.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: ${{ env.REQUIREMENTS }}
      - run: pip install -r "$REQUIREMENTS"
      - name: Build documentation
        run: mkdocs build --strict
        working-directory: docs/docs
      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        working-directory: docs/docs